### ISSUE TITLE
ShExJ LanguageStem should be STRING instead of ObjectLiteral

### ISSUE THREAD

**Issue by hsolbrig** [shexSpec/shex#54]
Currently, LanguageStem is represented as an ObjectLiteral, meaning that it has a _value_, an optional _language_ and an optional _type_.  This is an issue because:

1. ShExJ models this as LANGTAG, which does not represent language or type
2. I have no idea what should be done with something in the form: "stem":{"value" : "en", "language": "fr"}

Similarly, the _exclusions_ in LanguageStemRange include the possibility of an IRI.  Same issue - no equivalent in ShExC, as an exclusion is LANGTAG '~' and IRI's simply don't apply.

**Recommendation:**
 LanguageStem     { stem:~~ObjectLiteral~~STRING } 
 LanguageStemRange  { stem:(~~ObjectLiteral~~STRING|Wildcard) exclusions:[~~objectValue~~ STRING|LanguageStem +]? }

Results of this recommendation can be found: 
https://github.com/shexSpec/shexTest/compare/master...LanguageStem-string

**Alternative:**
Same change, but tighten up the parser rules on LANGTAG:

ObjectLiteral  {value:STRING language:~~STRING~~LANGTAG? type:STRING? }

 LanguageStem     { stem:~~ObjectLiteral~~LANGTAG } 
 LanguageStemRange  { stem:(~~ObjectLiteral~~LANGTAG|Wildcard) exclusions:[~~objectValue~~ LANGTAG|LanguageStem +]? }
LANGTAG : ([a-zA-Z])+ ("-" ([a-zA-Z0-9])+)*

**Comment by gkellogg** [comment]
As ShExJ is JSON-LD, all values are interpreted either as IRI, BNode, or Literal. In some cases, we can use a string value for a property, but only if that property is not described in the context to contain an IRI. Currently, the context defines “stem” as “xsd:anyUri”, and “exclusions” as “@type”: “@id”, as that is the sense for their use in IRIs. JSON-LD 1.0 doesn’t have a way to override this without using the expanded version (thus: {“value”: “fr-“}, for example).

We have discussed going to JSON-LD 1.1 (still in progress as a community project), which does allow us to [override term definitions based on, for example, “@type”](http://json-ld.org/spec/latest/json-ld/#scoped-contexts). So, we could describe one sense for “stem” and “exclusions” when used with “IriStem”, and another when used with “LanguageStem”.

Another reason to use JSON-LD 1.1 is because of it's support of [id maps](http://json-ld.org/spec/latest/json-ld/#node-identifier-indexing), which would allow the schema to use an object to describe shapes, much as the pre JSON-LD version did.

Until we do this, changing `LanguageStem` and `LanguageStemRange` (along with `LiteralStem` and `LiteralStemRange`) will not work with the JSON-LD/ShExR interpretation.

**Comment by ericprud** [comment]
What if we say that stems are all strings (no xsd:anyUri)?

**Comment by gkellogg** [comment]
We'd need to do that for both stems and exclusions, but it should work. That would change ShExC as well, I think.

**Comment by ericprud** [comment]
I made a IriStem-string branches in [shexTest](https://github.com/shexSpec/shexTest/tree/IriStem-string) and [shex.js](https://github.com/shexSpec/shex.js/tree/IriStem-string) which treat all stems as strings and round-trips to ShExC.

**Comment by ericprud** [comment]
closed in meeting 14 April 2017 meeting
